apiVersion: v1
kind: Pod
metadata:
  name: javaapi
spec:
  containers:
    - image: docker.io/bbachin1/java-api
      name: javaapi
      imagePullPolicy: Always
      resources: {}
      ports:
        - containerPort: 8080